### ISSUE TITLE
Bot logs conversation in discord to squadjs console

### ISSUE THREAD

**Issue by lbzepoqo** [fantinodavide/squadjs-alt-checker#1]
Our console is a bit spammy now 😂

![image](https://github.com/fantinodavide/squadjs-alt-checker/assets/49586590/1ef4cfdc-46ab-49fd-9702-8c46d1a80ab7)

**Comment by lbzepoqo** [comment]
#2

**Comment by fantinodavide** [comment]
Thank you @sergelouie6! Marking this issue as completed, https://github.com/fantinodavide/squadjs-alt-checker/pull/2 has been merged!
